call pathogen#infect()
call pathogen#helptags()

" Solarized
let g:solarized_termtrans=1
syntax enable
set background=dark
colorscheme solarized

set cursorline
set tw=0
set nocompatible
set autoindent
set cindent
set tabstop=4
set shiftwidth=4
set expandtab
set noerrorbells
set number
set nobackup
let NERDTreeWinSize=46
let mapleader="\\"

if version >= 703
   map <Leader>n :if &number <Bar>
               \set relativenumber <Bar>
               \else <Bar>
               \set number <Bar>
               \endif <cr>
endif
set ruler

"Syntastic
let g:syntastic_check_on_wq=0
let g:syntastic_enable_balloons=0
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_ignore_files=['.*\.py$']
let g:syntastic_javascript_checkers = ['jsl']
let g:syntastic_css_checkers = ['csslint']

filetype plugin indent on

:imap <Esc>Oq 1
:imap <Esc>Or 2
:imap <Esc>Os 3
:imap <Esc>Ot 4
:imap <Esc>Ou 5
:imap <Esc>Ov 6
:imap <Esc>Ow 7
:imap <Esc>Ox 8
:imap <Esc>Oy 9
:imap <Esc>Op 0
:imap <Esc>On .
:imap <Esc>OQ /
:imap <Esc>OR *
:imap <Esc>Ol +
:imap <Esc>OS -

set showmode

highlight ModeMsg guibg=blue guifg=green gui=NONE cterm=NONE term=NONE

au! BufNewFile,BufRead *.gob set filetype=cpp
au! BufNewFile,BufRead *.dbk set filetype=xml
filetype on
set ai
set showmatch

set wildignore=*.o,*.obj,*.class,*~,.bak

"if has('gui')
"        copen 5
"endif

set foldmethod=indent
set foldlevel=0
set foldcolumn=1

let &cdpath=','.expand("$HOME")

noremap <space> <C-f>

let Tlist_Use_Right_Window=1
if has('gui')
        let Tlist_Auto_Open=1
endif
let Tlist_Enable_Fold_Column=0
let Tlist_Compact_Format=1
let Tlist_WinWidth=28
let Tlist_Exit_OnlyWindow=1
let Tlist_File_Fold_Auto_Close = 0


iab teh the
iab seperate separate
iab probalem problem

if has("autocmd")
    filetype plugin indent on
endif

set autowrite
set incsearch
set showmatch

set nofoldenable
set foldmethod=indent
set autoread
set backupext=.bak


set grepprg=grep\ -nH\ $*

let g:detectindent_preferred_expandtab = 1
let g:detectindent_preferred_indent = 4

let &guicursor = &guicursor . ",a:blinkon0"

autocmd BufRead,BufNewFile *.py,*.rscript syntax on set ft=python
autocmd BufRead,BufNewFile *.py,*.rscript set ai
autocmd BufRead,BufNewFile *.rscript,*.py,*sh set tabstop=4 expandtab shiftwidth=4
autocmd BufRead,BufNewFile *.lua,*.rb set tabstop=2 expandtab shiftwidth=2 
autocmd BufRead,BufNewFile *.rb syntax on set ft=ruby
autocmd BufRead,BufNewFile *.rb set ai

noremap <silent> <F6> :PyLintToggle<CR>
noremap <silent> <F7> :NERDTreeToggle<CR>
nnoremap <silent> <F8> :TlistToggle<CR>

noremap <silent> <F9> :TMiniBufExplorer<CR>
noremap <silent> <F10> :cal VimCommanderToggle()<CR>
nnoremap <silent> <F11> :YRShow<CR>

function GetYRElem(nr)
    :YRGetElem a:nr
endfunction

command -nargs=1 YG call GetYRElem(<f-args>)

let basedir = "/DATA/projects"
let domain = "be.venefyxatu.palm."
let appversion = "1.0.0"

function GenerateScene(basedir, project, name)
    exe '!palm-generate -t new_scene -p "name=' . a:name . '" ' . a:basedir . '/' . a:project
endfunction

command -nargs=+ Newscene call GenerateScene(basedir, <f-args>)

function Testrun(basedir, domain, appversion, project)
    call PackageApp(a:basedir, a:project)
    call InstallApp(a:domain, a:project, a:appversion)
    call LaunchApp(a:domain, a:project)
endfunction

function PackageApp(basedir, project)
    silent exe '!palm-package ' . a:basedir . '/' . a:project 
endfunction

function InstallApp(domain, project, appversion)
    silent exe '!palm-install ' . a:domain . a:project . '_' . a:appversion . '_all.ipk' 
endfunction

function LaunchApp(domain, project)
    silent exe '!palm-launch ' . a:domain . a:project 
endfunction

function RemoveApp(basedir, domain, appversion, project)
    silent exe '!palm-install -r ' . a:domain . a:project
    silent exe '!rm -f ' . a:basedir . '/' . a:project . '/' . a:domain . a:project . '_' . a:appversion . '_all.ipk'
endfunction

command -nargs=1 Testrun call Testrun(basedir, domain, appversion, <f-args>)
command -nargs=1 Cleanup call RemoveApp(basedir, domain, appversion, <f-args>)

set tw=0


let g:ctrlp_map = '<c-f>'


let pymode_rope_vim_completion=1
let pymode_rope_extended_complete=1

nnoremap <F5> :w<CR> :silent make<CR>
inoremap <F5> <Esc>:w<CR>:silent make<CR>
vnoremap <F5> :<C-U>:w<CR>:silent make<CR

noremap <F2> :w<CR> :!python ~/ABC/dacentec/source/clouddesktop-appcatalog/scripts/precommit.py && nosetests tests/libs/test_cifs_backend.py:CifsDriveBackendTestCase -x -s <CR>

"Python-mode config

" Enable python folding
let g:pymode_folding = 1
let g:pymode_lint_checker = "pyflakes,pep8,mccabe"
let g:pymode_lint_ignore = ""
