#!/bin/bash

# backlight brightness controls. use freely
# and adjust sysfs directory to your backlight type. 
# $author Brice Burgess @iceburg


# modified by Chris Rainey for a Lenovo ideacentre AIO 300-22ACL
# running openbox on Ubuntu 16.04
#sysfs="/sys/class/backlight/radeon_bl0"

# modified by Chris Rainey for a HP Notebook 15-ay039wm
# running openbox on Ubuntu 16.10
# sysfs="/sys/class/backlight/intel_backlight"


sysfs="/sys/class/backlight/amdgpu_bl0"


max=`cat ${sysfs}/max_brightness`
level=`cat ${sysfs}/brightness`


usage()
{
script=${0##*/}
echo
echo "Invalid usage of ${script}!"
echo "  $1"
echo "----------------"
echo "$script up     : increases brightness"
echo "$script down   : decreases brightness"
echo "$script set #  : sets brightness to # (integer)"
echo "----------------"
echo


exit 1
}

set_brightness()
{

level=$1

if [ $level -lt 1 ] ; then
 level=1
elif [ $level -gt $max ] ; then
 level=$max
fi
 
echo $level > $sysfs/brightness 
}

case "$1" in
  up)
    let "level+=50"
    set_brightness $level 
    ;;
  down)
    let "level-=50"
    set_brightness $level 
    ;;
  set)
    if [[ ! $2 =~ ^[[:digit:]]+$ ]]; then
     usage "second argument must be an integer"
    fi

    set_brightness $2
    ;;
  *)
    usage "invalid argument"
esac
